import { toast } from '../util.js'

function exportPack() {
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Audit Pack</title><style>body{font-family:Georgia,serif;color:#111;max-width:740px;margin:30px auto;padding:0 26px;line-height:1.5}h1{color:#1b4332;border-bottom:3px solid #2d6a4f;padding-bottom:6px}h2{font-size:13px;text-transform:uppercase;color:#2d6a4f;margin-top:20px}table{width:100%;border-collapse:collapse;font-size:12.5px;margin:6px 0}th,td{border-bottom:1px solid #ddd;padding:6px 9px;text-align:left}th{background:#eef3ec}.n{text-align:right}</style></head><body><h1>CarbonDesk Audit Pack — Creative Bliss Sdn Bhd, FY2026</h1><p>Prepared for accredited verifier review. GHG Protocol, Scope 2 location-based. Status: self-reported, verification pending.</p><h2>Emissions summary (FY2026)</h2><table><tr><th>Scope</th><th class="n">tCO2e</th></tr><tr><td>Scope 1</td><td class="n">139.2</td></tr><tr><td>Scope 2</td><td class="n">1,065.6</td></tr><tr><td>Scope 3</td><td class="n">1,489.2</td></tr><tr><td><b>Total</b></td><td class="n"><b>2,694.0</b></td></tr></table><h2>Emission factors</h2><table><tr><th>Source</th><th>Factor</th><th>Reference</th></tr><tr><td>Electricity</td><td>0.74 kg/kWh</td><td>Energy Commission / MGTC</td></tr><tr><td>Diesel</td><td>2.68 kg/L</td><td>DEFRA / IPCC</td></tr><tr><td>Steel</td><td>1.46 t/t</td><td>DEFRA / supplier</td></tr></table><h2>Change log</h2><table><tr><th>When</th><th>Who</th><th>Change</th></tr><tr><td>7 Jun 2026 14:02</td><td>K. Ng</td><td>Generated IFRS S2 draft</td></tr><tr><td>6 Jun 2026 16:45</td><td>Lim Wei</td><td>Grid factor 0.77 to 0.74</td></tr><tr><td>6 Jun 2026 09:10</td><td>System</td><td>Imported June electricity (TNB)</td></tr></table><p style="margin-top:24px;color:#999;font-size:11px">Generated by CarbonDesk · Demonstration data.</p></body></html>`
  const blob = new Blob(['﻿' + html], { type: 'application/msword' })
  const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'CarbonDesk_Audit_Pack_FY2026.doc'
  document.body.appendChild(a); a.click(); a.remove(); toast('Audit pack downloaded', '✓')
}
const LOG = [['7 Jun 14:02', 'K. Ng', 'Generated IFRS S2 draft'], ['7 Jun 11:20', 'K. Ng', 'Supplier MetalSource data received'], ['6 Jun 16:45', 'Lim Wei', 'Edited grid factor 0.77→0.74'], ['6 Jun 09:10', 'System', 'Imported June electricity (TNB)']]
export default function Audit() {
  return (
    <div className="content">
      <div className="page-head"><div><div className="eyebrow">✦ Data &amp; trust</div><h2>Audit &amp; <span>Verification</span></h2><p>The credibility layer — methodology on record, a change log, and an audit pack for your verifier.</p></div><button className="btn" onClick={exportPack}>⬇ Export audit pack</button></div>
      <div className="grid g3" style={{ marginBottom: 16 }}>
        <div className="card kpi"><div className="lab">Verification status</div><div className="val" style={{ fontSize: 18, color: 'var(--ember)' }}>Third-party pending</div></div>
        <div className="card kpi"><div className="lab">Methodology</div><div className="val" style={{ fontSize: 18 }}>GHG Protocol</div></div>
        <div className="card kpi"><div className="lab">Data quality</div><div className="val" style={{ fontSize: 18, color: 'var(--lime)' }}>Primary 68%</div></div>
      </div>
      <div className="grid g2">
        <div className="card"><div className="sec-title">Methodology statement</div><div className="sec-sub">Stated up front for the auditor</div>
          <p style={{ fontSize: 13, color: 'var(--slate)', lineHeight: 1.65 }}>Emissions calculated per the GHG Protocol Corporate Standard. Scope 2 location-based using the Peninsular Malaysia grid factor (0.74 kg CO₂/kWh). Fuel and material factors from DEFRA/IPCC. Scope 3 from primary supplier data where returned, otherwise category averages (flagged). No figure is machine-generated without a traceable factor.</p>
          <div className="note">Closing the credibility gap vs TÜV-certified / Big-4-backed rivals: align to a recognized standard, log every change, and hand the verifier a complete pack.</div></div>
        <div className="card"><div className="sec-title">Change log</div><div className="sec-sub">Every edit, who &amp; when</div>
          <table className="rtable"><thead><tr><th>When</th><th>Who</th><th>Change</th></tr></thead>
            <tbody>{LOG.map((r, i) => <tr key={i}><td className="n">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></div>
      </div>
    </div>
  )
}
